import { ApiProperty } from '@nestjs/swagger';
import { IsIn, IsISO8601, IsString, Length } from 'class-validator';

import type { PainelAdministracaoOperacional } from '../modelo-administracao-operacional.js';

class ContaOperacionalDto { @ApiProperty({ format: 'uuid' }) public readonly id: string; @ApiProperty() public readonly nome: string; @ApiProperty() public readonly estado: string; @ApiProperty({ required: false }) public readonly telefone_mascarado?: string; @ApiProperty() public readonly versao: number; public constructor(item: PainelAdministracaoOperacional['contas'][number]) { this.id = item.id; this.nome = item.nome; this.estado = item.estado; if (item.telefoneMascarado !== undefined) this.telefone_mascarado = item.telefoneMascarado; this.versao = item.versao; } }
class FilaOperacionalDto { @ApiProperty({ format: 'uuid' }) public readonly id: string; @ApiProperty() public readonly nome: string; @ApiProperty() public readonly estado: string; @ApiProperty() public readonly usuarios_ativos: number; @ApiProperty() public readonly atendimentos_abertos: number; @ApiProperty({ required: false }) public readonly calendario?: string; @ApiProperty({ required: false, type: Object }) public readonly sla?: PainelAdministracaoOperacional['filas'][number]['sla']; public constructor(item: PainelAdministracaoOperacional['filas'][number]) { this.id = item.id; this.nome = item.nome; this.estado = item.estado; this.usuarios_ativos = item.usuariosAtivos; this.atendimentos_abertos = item.atendimentosAbertos; if (item.calendario !== undefined) this.calendario = item.calendario; if (item.sla !== undefined) this.sla = item.sla; } }
class CalendarioOperacionalDto { @ApiProperty({ format: 'uuid' }) public readonly id: string; @ApiProperty() public readonly nome: string; @ApiProperty() public readonly fuso_horario: string; @ApiProperty() public readonly modo: string; @ApiProperty({ required: false, type: Object }) public readonly override_atual?: { readonly estado: string; readonly vigente_ate: string }; public constructor(item: PainelAdministracaoOperacional['calendarios'][number]) { this.id = item.id; this.nome = item.nome; this.fuso_horario = item.fusoHorario; this.modo = item.modo; if (item.overrideAtual !== undefined) this.override_atual = { estado: item.overrideAtual.estado, vigente_ate: item.overrideAtual.vigenteAte.toISOString() }; } }
class IntegracaoOperacionalDto { @ApiProperty() public readonly codigo: string; @ApiProperty({ enum: ['ATIVA', 'NAO_CONFIGURADA'] }) public readonly estado: 'ATIVA' | 'NAO_CONFIGURADA'; @ApiProperty() public readonly detalhe: string; public constructor(item: PainelAdministracaoOperacional['integracoes'][number]) { this.codigo = item.codigo; this.estado = item.estado; this.detalhe = item.detalhe; } }

export class PainelAdministracaoOperacionalDto {
  @ApiProperty({ type: Object }) public readonly capacidades: PainelAdministracaoOperacional['capacidades'];
  @ApiProperty({ type: [ContaOperacionalDto] }) public readonly contas: readonly ContaOperacionalDto[];
  @ApiProperty({ type: [FilaOperacionalDto] }) public readonly filas: readonly FilaOperacionalDto[];
  @ApiProperty({ type: [CalendarioOperacionalDto] }) public readonly calendarios: readonly CalendarioOperacionalDto[];
  @ApiProperty({ type: [IntegracaoOperacionalDto] }) public readonly integracoes: readonly IntegracaoOperacionalDto[];
  public constructor(item: PainelAdministracaoOperacional) { this.capacidades = item.capacidades; this.contas = item.contas.map((conta) => new ContaOperacionalDto(conta)); this.filas = item.filas.map((fila) => new FilaOperacionalDto(fila)); this.calendarios = item.calendarios.map((calendario) => new CalendarioOperacionalDto(calendario)); this.integracoes = item.integracoes.map((integracao) => new IntegracaoOperacionalDto(integracao)); }
}
export class EntradaCriacaoFilaOperacionalDto { @ApiProperty({ maxLength: 120 }) @IsString() @Length(1, 120) public readonly nome!: string; }
export class EntradaOverrideCalendarioOperacionalDto { @ApiProperty({ enum: ['ABERTO', 'FECHADO'] }) @IsIn(['ABERTO', 'FECHADO']) public readonly estado!: 'ABERTO' | 'FECHADO'; @ApiProperty({ maxLength: 500 }) @IsString() @Length(1, 500) public readonly motivo!: string; @ApiProperty({ format: 'date-time' }) @IsISO8601() public readonly vigente_de!: string; @ApiProperty({ format: 'date-time' }) @IsISO8601() public readonly vigente_ate!: string; }
