packages:
  - apps/*
  - packages/*

engineStrict: true
nodeLinker: hoisted
pmOnFail: error
saveExact: true
sharedWorkspaceLockfile: true
strictDepBuilds: true
verifyDepsBeforeRun: error

overrides:
  react: 19.2.3
  react-dom: 19.2.3
