packages:
  - apps/*
  - packages/*

engineStrict: true
nodeLinker: hoisted
pmOnFail: error
saveExact: true
sharedWorkspaceLockfile: true
strictDepBuilds: true
verifyDepsBeforeRun: error

overrides:
  deepmerge-ts: 8.0.2
  js-yaml: 4.3.2
  mysql2: 3.24.2
  react: 19.2.3
  react-dom: 19.2.3

allowBuilds:
  '@scarf/scarf': false
  '@prisma/engines': true
  prisma: true

minimumReleaseAgeExclude:
  - '@xyflow/react@12.11.6'
  - '@xyflow/system@0.0.82'
  - '@expo/cli@57.0.21'
  - '@expo/fingerprint@0.20.12'
  - '@expo/router-server@57.0.9'
  - babel-preset-expo@57.0.10
  - expo-asset@57.0.16
  - expo-constants@57.0.17
  - expo-dev-client@57.0.18
  - expo-dev-launcher@57.0.19
  - expo-dev-menu@57.0.18
  - expo-font@57.0.3
  - expo-modules-core@57.0.15
  - expo-modules-jsi@57.0.7
  - expo-notifications@57.0.16
  - expo-secure-store@57.0.3
  - expo@57.0.19
