// This file is auto-generated by @hey-api/openapi-ts

export { obterInformacoesApi, type Options, verificarAplicacaoPronta, verificarProcessoVivo } from './sdk.gen';
export type { ClientOptions, ErroCanonicoDto, EstadoSaudeDto, InformacoesApiDto, ObterInformacoesApiData, ObterInformacoesApiError, ObterInformacoesApiErrors, ObterInformacoesApiResponse, ObterInformacoesApiResponses, VerificarAplicacaoProntaData, VerificarAplicacaoProntaError, VerificarAplicacaoProntaErrors, VerificarAplicacaoProntaResponse, VerificarAplicacaoProntaResponses, VerificarProcessoVivoData, VerificarProcessoVivoResponse, VerificarProcessoVivoResponses } from './types.gen';
