// This file is auto-generated by @hey-api/openapi-ts

export { obterInformacoesApi, type Options } from './sdk.gen';
export type { ClientOptions, ErroCanonicoDto, InformacoesApiDto, ObterInformacoesApiData, ObterInformacoesApiError, ObterInformacoesApiErrors, ObterInformacoesApiResponse, ObterInformacoesApiResponses } from './types.gen';
