// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ErroCanonicoDto = {
    codigo: string;
    mensagem: string;
};

export type InformacoesApiDto = {
    nome: string;
    versao_api: string;
};

export type ObterInformacoesApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1';
};

export type ObterInformacoesApiErrors = {
    500: ErroCanonicoDto;
};

export type ObterInformacoesApiError = ObterInformacoesApiErrors[keyof ObterInformacoesApiErrors];

export type ObterInformacoesApiResponses = {
    200: InformacoesApiDto;
};

export type ObterInformacoesApiResponse = ObterInformacoesApiResponses[keyof ObterInformacoesApiResponses];
