// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ErroCanonicoDto = {
    codigo: string;
    mensagem: string;
    correlacao_id: string;
};

export type InformacoesApiDto = {
    nome: string;
    versao_api: string;
};

export type EstadoSaudeDto = {
    estado: 'VIVO' | 'PRONTO';
};

export type ContaOperacionalDto = {
    id: string;
    nome: string;
    estado: string;
    telefone_mascarado?: string;
    versao: number;
};

export type FilaOperacionalDto = {
    id: string;
    nome: string;
    estado: string;
    usuarios_ativos: number;
    atendimentos_abertos: number;
    calendario?: string;
    sla?: {
        [key: string]: unknown;
    };
};

export type CalendarioOperacionalDto = {
    id: string;
    nome: string;
    fuso_horario: string;
    modo: string;
    override_atual?: {
        [key: string]: unknown;
    };
};

export type IntegracaoOperacionalDto = {
    codigo: string;
    estado: 'ATIVA' | 'NAO_CONFIGURADA';
    detalhe: string;
};

export type PainelAdministracaoOperacionalDto = {
    capacidades: {
        [key: string]: unknown;
    };
    contas: Array<ContaOperacionalDto>;
    filas: Array<FilaOperacionalDto>;
    calendarios: Array<CalendarioOperacionalDto>;
    integracoes: Array<IntegracaoOperacionalDto>;
};

export type EntradaCriacaoFilaOperacionalDto = {
    nome: string;
};

export type EntradaOverrideCalendarioOperacionalDto = {
    estado: 'ABERTO' | 'FECHADO';
    motivo: string;
    vigente_de: string;
    vigente_ate: string;
};

export type EntradaResgatePareamentoQrDto = {
    token_qr: string;
    identificador_instalacao: string;
    segredo_vinculo: string;
    plataforma: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo: string;
};

export type ResgatePareamentoQrDto = {
    pareamento_id: string;
    comprovante_resgate: string;
    expira_em: string;
};

export type EntradaComprovantePareamentoQrDto = {
    pareamento_id: string;
    comprovante_resgate: string;
    identificador_instalacao: string;
    segredo_vinculo: string;
    plataforma: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo: string;
};

export type EstadoPareamentoQrMobileDto = {
    estado: 'AGUARDANDO_CONFIRMACAO' | 'CONFIRMADO';
    expira_em: string;
};

export type SessaoMobileDto = {
    sessao_id: string;
    usuario_id: string;
    dispositivo_id: string;
    nome_exibicao: string;
    token_acesso: string;
    token_refresh: string;
    acesso_expira_em: string;
    refresh_expira_em: string;
    dispositivo_substituido: boolean;
};

export type EntradaLoginMobileDto = {
    identificador: string;
    senha: string;
    identificador_instalacao: string;
    segredo_vinculo: string;
    plataforma: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo: string;
};

export type EntradaRefreshMobileDto = {
    token_refresh: string;
};

export type ResumoDispositivoMobileDto = {
    dispositivo_id: string;
    atual: boolean;
    plataforma: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo: string;
    ultimo_acesso_em: string;
    criado_em: string;
};

export type ContextoSessaoMobileDto = {
    sessao_id: string;
    usuario_id: string;
    dispositivo_id: string;
    nome_exibicao: string;
    acesso_expira_em: string;
};

export type PareamentoQrGeradoDto = {
    pareamento_id: string;
    token_qr: string;
    expira_em: string;
};

export type ResumoPareamentoQrWebDto = {
    pareamento_id: string;
    estado: 'AGUARDANDO_RESGATE' | 'AGUARDANDO_CONFIRMACAO' | 'CONFIRMADO';
    expira_em: string;
    plataforma?: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo?: string;
};

export type EntradaLoginWebDto = {
    /**
     * Confirma a substituição da sessão web ativa mais antiga quando o limite for alcançado.
     */
    confirmar_revogacao_sessao_mais_antiga?: boolean;
    identificador: string;
    senha: string;
};

export type SessaoWebDto = {
    sessao_id: string;
    usuario_id: string;
    nome_exibicao: string;
    expira_em: string;
};

export type ResumoSessaoWebDto = {
    sessao_id: string;
    atual: boolean;
    autenticada_em: string;
    ultima_atividade_em: string;
    expira_em: string;
};

export type PerfilResumoAdministracaoUsuarioDto = {
    id: string;
    nome: string;
    papel_base: string;
};

export type FilaAdministracaoUsuarioDto = {
    id: string;
    nome: string;
};

export type ResumoAdministracaoUsuarioDto = {
    id: string;
    nome_exibicao: string;
    estado: string;
    perfil?: PerfilResumoAdministracaoUsuarioDto;
    filas: Array<FilaAdministracaoUsuarioDto>;
    sessoes_web_ativas: number;
    dispositivos_mobile_ativos: number;
    versao_permissoes: number;
};

export type PermissaoPerfilAdministracaoDto = {
    codigo: string;
    efeito: 'CONCEDER' | 'NEGAR';
};

export type PerfilAdministracaoUsuarioDto = {
    id: string;
    nome: string;
    papel_base: string;
    permissoes: Array<PermissaoPerfilAdministracaoDto>;
};

export type ItemAuditoriaAdministracaoUsuarioDto = {
    id: string;
    acao: string;
    criado_em: string;
    entidade_id?: string;
    usuario_ator_id?: string;
};

export type PainelAdministracaoUsuariosDto = {
    usuarios: Array<ResumoAdministracaoUsuarioDto>;
    perfis: Array<PerfilAdministracaoUsuarioDto>;
    filas: Array<FilaAdministracaoUsuarioDto>;
    auditoria_recente: Array<ItemAuditoriaAdministracaoUsuarioDto>;
};

export type EntradaAlteracaoAcessoUsuarioDto = {
    perfil_id: string;
    fila_ids: Array<string>;
    versao_esperada: number;
};

export type ResultadoAlteracaoAcessoUsuarioDto = {
    versao_permissoes: number;
};

export type IdentidadeContatoWebDto = {
    bsuid?: string;
    nome_perfil?: string;
    nome_usuario?: string;
    telefone_mascarado?: string;
};

export type ContratoContatoWebDto = {
    id: string;
    situacao: string;
    servico?: string;
    endereco_resumido?: string;
};

export type VinculoContatoWebDto = {
    id: string;
    nome_exibicao: string;
    tipo: string;
    preferencial: boolean;
    origem: 'SNAPSHOT';
    estado_snapshot: 'ATUAL' | 'EXCLUIDO' | 'NAO_DISPONIVEL' | 'OBSOLETO';
    idade_snapshot_segundos?: number;
    documento_mascarado?: string;
    contratos: Array<ContratoContatoWebDto>;
};

export type DetalhesContatoWebDto = {
    atendimento_id: string;
    conversa_id: string;
    contato_id: string;
    fila_id: string;
    nome_exibicao: string;
    estado_contato: string;
    identidades: Array<IdentidadeContatoWebDto>;
    contexto?: {
        [key: string]: unknown;
    };
    protocolo?: string;
    contagens: {
        atendimentos?: number;
        midias?: number;
        notas?: number;
        ordens_servico?: number;
    };
    permissoes: {
        [key: string]: boolean;
    };
    vinculos: Array<VinculoContatoWebDto>;
};

export type EntradaAlterarContextoWebDto = {
    vinculo_cliente_id: string;
    vinculo_contrato_id?: string;
    versao_esperada: number;
};

export type ResultadoFinanceiroContatoWebDto = {
    origem: 'INDISPONIVEL' | 'TEMPO_REAL';
    codigo?: string;
    faturas: Array<{
        referencia?: string;
        situacao?: string;
        valor_centavos?: number;
        vencimento?: string;
    }>;
};

export type EntradaPrepararAcaoErpWebDto = {
    acao: 'CRIAR_ORDEM_SERVICO' | 'EXECUTAR_DESBLOQUEIO';
};

export type PreviaAcaoErpWebDto = {
    acao: 'CRIAR_ORDEM_SERVICO' | 'EXECUTAR_DESBLOQUEIO';
    confirmacao_obrigatoria: boolean;
    disponivel: boolean;
    motivo?: string;
    resumo: Array<{
        rotulo?: string;
        valor?: string;
    }>;
};

export type EntradaExecutarAcaoErpWebDto = {
    acao: 'CRIAR_ORDEM_SERVICO' | 'EXECUTAR_DESBLOQUEIO';
    chave_idempotencia: string;
    confirmacao_explicita: true;
    assunto?: string;
    descricao?: string;
};

export type ResultadoAcaoErpWebDto = {
    situacao: string;
    operacao_id?: string;
};

export type ResultadoBuscaConversaWebDto = {
    id: string;
    atendimento_id: string;
    conta_whatsapp_nome: string;
    direcao: 'ENTRADA' | 'SAIDA';
    ocorrido_em: string;
    trecho: string;
    tipo_mensagem: string;
};

export type PaginaBuscaConversaWebDto = {
    itens: Array<ResultadoBuscaConversaWebDto>;
    proximo_cursor?: string;
};

export type ItemGaleriaConversaWebDto = {
    id: string;
    atendimento_id: string;
    ocorrido_em: string;
    tipo: 'DOCUMENTOS' | 'LINKS' | 'MIDIAS';
    tipo_mensagem: string;
    trecho?: string;
    mime?: string;
    tamanho_bytes?: number;
};

export type PaginaGaleriaConversaWebDto = {
    itens: Array<ItemGaleriaConversaWebDto>;
    proximo_cursor?: string;
};

export type ResumoAtendimentoWebDto = {
    atendimento_id: string;
    conversa_id: string;
    contato_id: string;
    conta_whatsapp_id: string;
    nome_contato: string;
    identidade_secundaria?: string;
    fila_id: string;
    fila_nome: string;
    modo: 'BOT' | 'HUMANO';
    estado: 'AGUARDANDO' | 'EM_ATENDIMENTO';
    ultima_atividade_em: string;
    ultima_mensagem_resumo: string;
    ultima_mensagem_direcao?: 'ENTRADA' | 'SAIDA';
    quantidade_nao_lida: number;
    sla_em?: string;
    janela_expira_em?: string;
};

export type ListaAtendimentosWebDto = {
    itens: Array<ResumoAtendimentoWebDto>;
    filtro: 'MEUS' | 'PENDENTES' | 'NAO_LIDOS' | 'SLA' | 'EXPIRANDO' | 'EM_AUTOMACAO';
};

export type RespostaRapidaWebDto = {
    id: string;
    titulo: string;
    atalho: string;
    texto: string;
};

export type ModeloAprovadoWebDto = {
    id: string;
    nome: string;
    idioma: string;
    quantidade_parametros: number;
};

export type EntradaEnvioTextoWebDto = {
    mensagem_cliente_id: string;
    texto: string;
    responde_a_mensagem_id?: string;
};

export type MensagemCriadaWebDto = {
    id: string;
    estado: string;
    recebida_servidor_em: string;
};

export type EntradaReacaoWebDto = {
    mensagem_cliente_id: string;
    mensagem_alvo_id: string;
    emoji: '👍' | '❤️' | '😂' | '😮' | '😢' | '🙏';
};

export type EntradaEnvioModeloWebDto = {
    mensagem_cliente_id: string;
    modelo_id: string;
    parametros: Array<string>;
};

export type ItemTimelineWebDto = {
    id: string;
    tipo: 'EVENTO_OPERACIONAL' | 'FORMULARIO' | 'MENSAGEM' | 'NOTA_INTERNA' | 'SEPARADOR_ATENDIMENTO';
    ocorrido_em: string;
    atendimento_id: string;
    conta_whatsapp_nome?: string;
    direcao?: 'ENTRADA' | 'SAIDA';
    estado_mensagem?: string;
    mensagem_tipo?: string;
    texto?: string;
    rotulo?: string;
    somente_equipe?: boolean;
    responde_a_mensagem_id?: string;
    citacao_texto?: string;
    reacoes?: Array<{
        emoji?: string;
        somente_interna?: boolean;
    }>;
};

export type PaginaTimelineWebDto = {
    itens: Array<ItemTimelineWebDto>;
    proximo_cursor?: string;
    marcador: {
        [key: string]: unknown;
    };
};

export type EntradaLeituraTimelineWebDto = {
    mensagem_id: string;
    versao_esperada: number;
};

export type MarcadorLeituraWebDto = {
    versao: number;
};

export type EntradaMarcarNaoLidaWebDto = {
    versao_esperada: number;
};

export type VersaoFluxoEditorDto = {
    id: string;
    fluxo_id: string;
    numero_versao: number;
    estado: 'RASCUNHO' | 'EM_TESTE' | 'PUBLICADA' | 'ARQUIVADA';
    revisao: number;
    versao_schema_definicao: number;
    definicao: {
        [key: string]: unknown;
    };
    atualizada_em: string;
    publicada_em?: string;
};

export type FluxoEditorDto = {
    id: string;
    nome: string;
    descricao?: string;
    tipo: 'ATENDIMENTO' | 'AUTENTICACAO' | 'FINANCEIRO' | 'COMERCIAL' | 'SUPORTE' | 'OUTRO';
    ativo: boolean;
    revisao: number;
    versao_publicada_id?: string;
    atualizado_em: string;
    versoes: Array<VersaoFluxoEditorDto>;
};

export type EntradaSimulacaoFluxoDto = {
    definicao: {
        [key: string]: unknown;
    };
    cenario: 'CAMINHO_FELIZ' | 'CAMINHO_ALTERNATIVO' | 'CONTATO_NAO_IDENTIFICADO' | 'ERP_INDISPONIVEL' | 'TIMEOUT' | 'FORA_DO_HORARIO' | 'CANAL_LIMITADO';
};

export type ContextoFicticioSimulacaoFluxoDto = {
    contato: string;
    contrato: string;
    documento: string;
    telefone: string;
};

export type PassoSimulacaoFluxoDto = {
    ordem: number;
    no_id: string;
    tipo_no: string;
    estado: 'CONCLUIDO' | 'INTERROMPIDO';
    saida?: string;
    descricao: string;
};

export type ItemPreviaSimulacaoFluxoDto = {
    ordem_passo: number;
    origem: 'CLIENTE_FICTICIO' | 'EMPRESA' | 'SISTEMA';
    conteudo: string;
};

export type ResultadoSimulacaoFluxoDto = {
    cenario: 'CAMINHO_FELIZ' | 'CAMINHO_ALTERNATIVO' | 'CONTATO_NAO_IDENTIFICADO' | 'ERP_INDISPONIVEL' | 'TIMEOUT' | 'FORA_DO_HORARIO' | 'CANAL_LIMITADO';
    estado: 'CONCLUIDA' | 'INTERROMPIDA' | 'LIMITE_ATINGIDO';
    codigo_final: string;
    contexto_ficticio: ContextoFicticioSimulacaoFluxoDto;
    efeitos_reais_executados: false;
    passos: Array<PassoSimulacaoFluxoDto>;
    previa: Array<ItemPreviaSimulacaoFluxoDto>;
};

export type EntradaCriacaoFluxoEditorDto = {
    nome: string;
    descricao?: string;
    tipo: 'ATENDIMENTO' | 'AUTENTICACAO' | 'FINANCEIRO' | 'COMERCIAL' | 'SUPORTE' | 'OUTRO';
    definicao: {
        [key: string]: unknown;
    };
};

export type FluxoCriadoEditorDto = {
    fluxo: FluxoEditorDto;
    versao: VersaoFluxoEditorDto;
};

export type EntradaNovaVersaoFluxoEditorDto = {
    definicao: {
        [key: string]: unknown;
    };
    versao_schema_definicao: number;
};

export type EntradaSalvarRascunhoFluxoDto = {
    definicao: {
        [key: string]: unknown;
    };
    versao_schema_definicao: number;
    revisao_esperada: number;
};

export type EntradaRevisaoVersaoFluxoDto = {
    revisao_esperada: number;
};

export type ProblemaValidacaoFluxoDto = {
    codigo: string;
    no_id?: string;
    referencia_id?: string;
    variavel?: string;
};

export type ResultadoPreparacaoFluxoDto = {
    estado: 'EM_TESTE';
    fluxo_id: string;
    versao_fluxo_id: string;
    revisao_versao: number;
    valido: boolean;
    quantidade_nos: number;
    quantidade_conexoes: number;
    problemas: Array<ProblemaValidacaoFluxoDto>;
};

export type EntradaRevisaoFluxoDto = {
    revisao_fluxo_esperada: number;
};

export type ResultadoPublicacaoFluxoDto = {
    fluxo_id: string;
    tipo: 'PUBLICACAO' | 'ARQUIVAMENTO' | 'REVERSAO';
    revisao_fluxo: number;
    versao_anterior_id?: string;
    versao_publicada_id?: string;
};

export type EntradaAvaliacaoVersaoMobileDto = {
    plataforma: 'IOS' | 'ANDROID';
    versao_aplicativo: string;
};

export type AvaliacaoPoliticaVersaoMobileDto = {
    plataforma: 'IOS' | 'ANDROID';
    versao_informada: string;
    versao_minima: string;
    versao_recomendada: string;
    atualizacao_obrigatoria: boolean;
    atualizacao_recomendada: boolean;
    mensagem?: string;
    url_loja?: string;
};

export type ConfiguracaoClienteMobileDto = {
    politica: AvaliacaoPoliticaVersaoMobileDto;
    controles_recurso: {
        [key: string]: boolean;
    };
};

export type ConfiguracaoClienteWebDto = {
    controles_recurso: {
        [key: string]: boolean;
    };
};

export type ControleRecursoDto = {
    id: string;
    codigo: string;
    estado: 'ATIVADO' | 'DESATIVADO';
    desligado_emergencialmente: boolean;
    liberar_administradores: boolean;
    percentual_liberacao: number;
    usuarios_alvo: Array<string>;
    filas_alvo: Array<string>;
    versao: number;
};

export type PoliticaVersaoMobileDto = {
    plataforma: 'IOS' | 'ANDROID';
    versao_minima: string;
    versao_recomendada: string;
    mensagem?: string;
    url_loja?: string;
    versao: number;
};

export type AdministracaoReleasesDto = {
    controles: Array<ControleRecursoDto>;
    politicas_mobile: Array<PoliticaVersaoMobileDto>;
};

export type EntradaAtualizacaoControleRecursoDto = {
    estado: 'ATIVADO' | 'DESATIVADO';
    desligado_emergencialmente: boolean;
    liberar_administradores: boolean;
    percentual_liberacao: number;
    usuarios_alvo: Array<string>;
    filas_alvo: Array<string>;
    versao_esperada: number;
};

export type EntradaAtualizacaoPoliticaVersaoMobileDto = {
    versao_minima: string;
    versao_recomendada: string;
    mensagem?: string;
    url_loja?: string;
    versao_esperada: number;
};

export type SnapshotSincronizacaoDto = {
    sequencia_base: string;
    versao_permissoes: number;
    gerado_em: string;
    permissoes: Array<string>;
    filas: Array<{
        [key: string]: unknown;
    }>;
    atendimentos: Array<{
        [key: string]: unknown;
    }>;
    conversas: Array<{
        [key: string]: unknown;
    }>;
    mensagens_recentes: Array<{
        [key: string]: unknown;
    }>;
    notas_internas_recentes: Array<{
        [key: string]: unknown;
    }>;
    controles_recurso: {
        [key: string]: boolean;
    };
    politicas_versao: Array<{
        [key: string]: unknown;
    }>;
};

export type LoteSincronizacaoDto = {
    eventos: Array<{
        [key: string]: unknown;
    }>;
    sequencia_final: string;
    tem_mais: boolean;
};

export type ObterInformacoesApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1';
};

export type ObterInformacoesApiErrors = {
    500: ErroCanonicoDto;
};

export type ObterInformacoesApiError = ObterInformacoesApiErrors[keyof ObterInformacoesApiErrors];

export type ObterInformacoesApiResponses = {
    200: InformacoesApiDto;
};

export type ObterInformacoesApiResponse = ObterInformacoesApiResponses[keyof ObterInformacoesApiResponses];

export type VerificarProcessoVivoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/saude/vivo';
};

export type VerificarProcessoVivoResponses = {
    200: EstadoSaudeDto;
};

export type VerificarProcessoVivoResponse = VerificarProcessoVivoResponses[keyof VerificarProcessoVivoResponses];

export type VerificarAplicacaoProntaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/saude/pronto';
};

export type VerificarAplicacaoProntaErrors = {
    503: ErroCanonicoDto;
};

export type VerificarAplicacaoProntaError = VerificarAplicacaoProntaErrors[keyof VerificarAplicacaoProntaErrors];

export type VerificarAplicacaoProntaResponses = {
    200: EstadoSaudeDto;
};

export type VerificarAplicacaoProntaResponse = VerificarAplicacaoProntaResponses[keyof VerificarAplicacaoProntaResponses];

export type ListarAdministracaoOperacionalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/administracao/operacao';
};

export type ListarAdministracaoOperacionalResponses = {
    200: PainelAdministracaoOperacionalDto;
};

export type ListarAdministracaoOperacionalResponse = ListarAdministracaoOperacionalResponses[keyof ListarAdministracaoOperacionalResponses];

export type CriarFilaAdministracaoOperacionalData = {
    body: EntradaCriacaoFilaOperacionalDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/administracao/operacao/filas';
};

export type CriarFilaAdministracaoOperacionalResponses = {
    200: PainelAdministracaoOperacionalDto;
};

export type CriarFilaAdministracaoOperacionalResponse = CriarFilaAdministracaoOperacionalResponses[keyof CriarFilaAdministracaoOperacionalResponses];

export type InativarFilaAdministracaoOperacionalData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        filaId: string;
    };
    query?: never;
    url: '/api/v1/administracao/operacao/filas/{filaId}/inativar';
};

export type InativarFilaAdministracaoOperacionalResponses = {
    204: void;
};

export type InativarFilaAdministracaoOperacionalResponse = InativarFilaAdministracaoOperacionalResponses[keyof InativarFilaAdministracaoOperacionalResponses];

export type DefinirOverrideCalendarioAdministracaoOperacionalData = {
    body: EntradaOverrideCalendarioOperacionalDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        calendarioId: string;
    };
    query?: never;
    url: '/api/v1/administracao/operacao/calendarios/{calendarioId}/override';
};

export type DefinirOverrideCalendarioAdministracaoOperacionalResponses = {
    200: PainelAdministracaoOperacionalDto;
};

export type DefinirOverrideCalendarioAdministracaoOperacionalResponse = DefinirOverrideCalendarioAdministracaoOperacionalResponses[keyof DefinirOverrideCalendarioAdministracaoOperacionalResponses];

export type ResgatarPareamentoQrMobileData = {
    body: EntradaResgatePareamentoQrDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/pareamentos-qr/resgatar';
};

export type ResgatarPareamentoQrMobileResponses = {
    200: ResgatePareamentoQrDto;
};

export type ResgatarPareamentoQrMobileResponse = ResgatarPareamentoQrMobileResponses[keyof ResgatarPareamentoQrMobileResponses];

export type ConsultarPareamentoQrMobileData = {
    body: EntradaComprovantePareamentoQrDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/pareamentos-qr/consultar';
};

export type ConsultarPareamentoQrMobileResponses = {
    200: EstadoPareamentoQrMobileDto;
};

export type ConsultarPareamentoQrMobileResponse = ConsultarPareamentoQrMobileResponses[keyof ConsultarPareamentoQrMobileResponses];

export type ConcluirPareamentoQrMobileData = {
    body: EntradaComprovantePareamentoQrDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/pareamentos-qr/concluir';
};

export type ConcluirPareamentoQrMobileResponses = {
    200: SessaoMobileDto;
};

export type ConcluirPareamentoQrMobileResponse = ConcluirPareamentoQrMobileResponses[keyof ConcluirPareamentoQrMobileResponses];

export type EntrarSessaoMobileData = {
    body: EntradaLoginMobileDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/entrar';
};

export type EntrarSessaoMobileResponses = {
    200: SessaoMobileDto;
};

export type EntrarSessaoMobileResponse = EntrarSessaoMobileResponses[keyof EntrarSessaoMobileResponses];

export type RenovarSessaoMobileData = {
    body: EntradaRefreshMobileDto;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/renovar';
};

export type RenovarSessaoMobileResponses = {
    200: SessaoMobileDto;
};

export type RenovarSessaoMobileResponse = RenovarSessaoMobileResponses[keyof RenovarSessaoMobileResponses];

export type ListarDispositivosMobileData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/dispositivos';
};

export type ListarDispositivosMobileResponses = {
    200: Array<ResumoDispositivoMobileDto>;
};

export type ListarDispositivosMobileResponse = ListarDispositivosMobileResponses[keyof ListarDispositivosMobileResponses];

export type RevogarDispositivoMobileDoUsuarioData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path: {
        dispositivoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/mobile/dispositivos/{dispositivoId}/revogar';
};

export type RevogarDispositivoMobileDoUsuarioResponses = {
    204: void;
};

export type RevogarDispositivoMobileDoUsuarioResponse = RevogarDispositivoMobileDoUsuarioResponses[keyof RevogarDispositivoMobileDoUsuarioResponses];

export type ObterSessaoMobileData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/sessao';
};

export type ObterSessaoMobileResponses = {
    200: ContextoSessaoMobileDto;
};

export type ObterSessaoMobileResponse = ObterSessaoMobileResponses[keyof ObterSessaoMobileResponses];

export type SairSessaoMobileData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/sair';
};

export type SairSessaoMobileResponses = {
    204: void;
};

export type SairSessaoMobileResponse = SairSessaoMobileResponses[keyof SairSessaoMobileResponses];

export type GerarPareamentoQrWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/pareamentos-qr';
};

export type GerarPareamentoQrWebResponses = {
    201: PareamentoQrGeradoDto;
};

export type GerarPareamentoQrWebResponse = GerarPareamentoQrWebResponses[keyof GerarPareamentoQrWebResponses];

export type ConsultarPareamentoQrWebData = {
    body?: never;
    path: {
        pareamentoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/pareamentos-qr/{pareamentoId}';
};

export type ConsultarPareamentoQrWebResponses = {
    200: ResumoPareamentoQrWebDto;
};

export type ConsultarPareamentoQrWebResponse = ConsultarPareamentoQrWebResponses[keyof ConsultarPareamentoQrWebResponses];

export type ConfirmarPareamentoQrWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        pareamentoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/pareamentos-qr/{pareamentoId}/confirmar';
};

export type ConfirmarPareamentoQrWebResponses = {
    204: void;
};

export type ConfirmarPareamentoQrWebResponse = ConfirmarPareamentoQrWebResponses[keyof ConfirmarPareamentoQrWebResponses];

export type CancelarPareamentoQrWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        pareamentoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/pareamentos-qr/{pareamentoId}/cancelar';
};

export type CancelarPareamentoQrWebResponses = {
    204: void;
};

export type CancelarPareamentoQrWebResponse = CancelarPareamentoQrWebResponses[keyof CancelarPareamentoQrWebResponses];

export type EntrarSessaoWebData = {
    body: EntradaLoginWebDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/entrar';
};

export type EntrarSessaoWebResponses = {
    200: SessaoWebDto;
};

export type EntrarSessaoWebResponse = EntrarSessaoWebResponses[keyof EntrarSessaoWebResponses];

export type ListarSessoesWebData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sessoes';
};

export type ListarSessoesWebResponses = {
    200: Array<ResumoSessaoWebDto>;
};

export type ListarSessoesWebResponse = ListarSessoesWebResponses[keyof ListarSessoesWebResponses];

export type ObterSessaoWebData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sessao';
};

export type ObterSessaoWebResponses = {
    200: SessaoWebDto;
};

export type ObterSessaoWebResponse = ObterSessaoWebResponses[keyof ObterSessaoWebResponses];

export type RotacionarSessaoWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/rotacionar';
};

export type RotacionarSessaoWebResponses = {
    200: SessaoWebDto;
};

export type RotacionarSessaoWebResponse = RotacionarSessaoWebResponses[keyof RotacionarSessaoWebResponses];

export type SairSessaoWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sair';
};

export type SairSessaoWebResponses = {
    204: void;
};

export type SairSessaoWebResponse = SairSessaoWebResponses[keyof SairSessaoWebResponses];

export type SairTodasSessoesWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sair-todas';
};

export type SairTodasSessoesWebResponses = {
    204: void;
};

export type SairTodasSessoesWebResponse = SairTodasSessoesWebResponses[keyof SairTodasSessoesWebResponses];

export type RevogarSessaoWebDoUsuarioData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        sessaoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/sessoes/{sessaoId}/revogar';
};

export type RevogarSessaoWebDoUsuarioResponses = {
    204: void;
};

export type RevogarSessaoWebDoUsuarioResponse = RevogarSessaoWebDoUsuarioResponses[keyof RevogarSessaoWebDoUsuarioResponses];

export type RevogarSessoesWebAdministrativamenteData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        usuarioId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/usuarios/{usuarioId}/revogar-sessoes';
};

export type RevogarSessoesWebAdministrativamenteResponses = {
    204: void;
};

export type RevogarSessoesWebAdministrativamenteResponse = RevogarSessoesWebAdministrativamenteResponses[keyof RevogarSessoesWebAdministrativamenteResponses];

export type RevogarDispositivosMobileAdministrativamenteData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        usuarioId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/usuarios/{usuarioId}/revogar-dispositivos-mobile';
};

export type RevogarDispositivosMobileAdministrativamenteResponses = {
    204: void;
};

export type RevogarDispositivosMobileAdministrativamenteResponse = RevogarDispositivosMobileAdministrativamenteResponses[keyof RevogarDispositivosMobileAdministrativamenteResponses];

export type ListarAdministracaoUsuariosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/administracao/usuarios';
};

export type ListarAdministracaoUsuariosResponses = {
    200: PainelAdministracaoUsuariosDto;
};

export type ListarAdministracaoUsuariosResponse = ListarAdministracaoUsuariosResponses[keyof ListarAdministracaoUsuariosResponses];

export type AlterarAcessoUsuarioAdministracaoData = {
    body: EntradaAlteracaoAcessoUsuarioDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        usuarioId: string;
    };
    query?: never;
    url: '/api/v1/administracao/usuarios/{usuarioId}/acesso';
};

export type AlterarAcessoUsuarioAdministracaoResponses = {
    200: ResultadoAlteracaoAcessoUsuarioDto;
};

export type AlterarAcessoUsuarioAdministracaoResponse = AlterarAcessoUsuarioAdministracaoResponses[keyof AlterarAcessoUsuarioAdministracaoResponses];

export type ObterDetalhesContatoWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/contato';
};

export type ObterDetalhesContatoWebResponses = {
    200: DetalhesContatoWebDto;
};

export type ObterDetalhesContatoWebResponse = ObterDetalhesContatoWebResponses[keyof ObterDetalhesContatoWebResponses];

export type AlterarContextoContatoWebData = {
    body: EntradaAlterarContextoWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/contexto';
};

export type AlterarContextoContatoWebResponses = {
    200: DetalhesContatoWebDto;
};

export type AlterarContextoContatoWebResponse = AlterarContextoContatoWebResponses[keyof AlterarContextoContatoWebResponses];

export type ConsultarFinanceiroContatoWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/financeiro';
};

export type ConsultarFinanceiroContatoWebResponses = {
    200: ResultadoFinanceiroContatoWebDto;
};

export type ConsultarFinanceiroContatoWebResponse = ConsultarFinanceiroContatoWebResponses[keyof ConsultarFinanceiroContatoWebResponses];

export type PrepararAcaoErpContatoWebData = {
    body: EntradaPrepararAcaoErpWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/acoes-erp/preparar';
};

export type PrepararAcaoErpContatoWebResponses = {
    200: PreviaAcaoErpWebDto;
};

export type PrepararAcaoErpContatoWebResponse = PrepararAcaoErpContatoWebResponses[keyof PrepararAcaoErpContatoWebResponses];

export type ExecutarAcaoErpContatoWebData = {
    body: EntradaExecutarAcaoErpWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/acoes-erp/executar';
};

export type ExecutarAcaoErpContatoWebResponses = {
    200: ResultadoAcaoErpWebDto;
};

export type ExecutarAcaoErpContatoWebResponse = ExecutarAcaoErpContatoWebResponses[keyof ExecutarAcaoErpContatoWebResponses];

export type BuscarConversaWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query: {
        cursor?: string;
        termo: unknown;
    };
    url: '/api/v1/web/atendimentos/{atendimentoId}/busca';
};

export type BuscarConversaWebResponses = {
    200: PaginaBuscaConversaWebDto;
};

export type BuscarConversaWebResponse = BuscarConversaWebResponses[keyof BuscarConversaWebResponses];

export type ListarGaleriaConversaWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query: {
        cursor?: string;
        tipo: 'MIDIAS' | 'LINKS' | 'DOCUMENTOS';
    };
    url: '/api/v1/web/atendimentos/{atendimentoId}/galeria';
};

export type ListarGaleriaConversaWebResponses = {
    200: PaginaGaleriaConversaWebDto;
};

export type ListarGaleriaConversaWebResponse = ListarGaleriaConversaWebResponses[keyof ListarGaleriaConversaWebResponses];

export type ListarAtendimentosWebData = {
    body?: never;
    path?: never;
    query?: {
        filtro?: 'MEUS' | 'PENDENTES' | 'NAO_LIDOS' | 'SLA' | 'EXPIRANDO' | 'EM_AUTOMACAO';
    };
    url: '/api/v1/web/atendimentos';
};

export type ListarAtendimentosWebResponses = {
    200: ListaAtendimentosWebDto;
};

export type ListarAtendimentosWebResponse = ListarAtendimentosWebResponses[keyof ListarAtendimentosWebResponses];

export type ListarRespostasRapidasWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query?: {
        busca?: string;
    };
    url: '/api/v1/web/atendimentos/{atendimentoId}/respostas-rapidas';
};

export type ListarRespostasRapidasWebResponses = {
    200: Array<RespostaRapidaWebDto>;
};

export type ListarRespostasRapidasWebResponse = ListarRespostasRapidasWebResponses[keyof ListarRespostasRapidasWebResponses];

export type ListarModelosAprovadosWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query?: {
        busca?: string;
    };
    url: '/api/v1/web/atendimentos/{atendimentoId}/modelos-aprovados';
};

export type ListarModelosAprovadosWebResponses = {
    200: Array<ModeloAprovadoWebDto>;
};

export type ListarModelosAprovadosWebResponse = ListarModelosAprovadosWebResponses[keyof ListarModelosAprovadosWebResponses];

export type EnviarTextoWebData = {
    body: EntradaEnvioTextoWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/mensagens/texto';
};

export type EnviarTextoWebResponses = {
    200: MensagemCriadaWebDto;
};

export type EnviarTextoWebResponse = EnviarTextoWebResponses[keyof EnviarTextoWebResponses];

export type EnviarMidiaWebData = {
    body: {
        arquivo: Blob | File;
        mensagem_cliente_id: string;
    };
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/mensagens/midia';
};

export type EnviarMidiaWebResponses = {
    200: MensagemCriadaWebDto;
};

export type EnviarMidiaWebResponse = EnviarMidiaWebResponses[keyof EnviarMidiaWebResponses];

export type ReagirMensagemWebData = {
    body: EntradaReacaoWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/mensagens/reacao';
};

export type ReagirMensagemWebResponses = {
    200: MensagemCriadaWebDto;
};

export type ReagirMensagemWebResponse = ReagirMensagemWebResponses[keyof ReagirMensagemWebResponses];

export type BaixarMidiaWebData = {
    body?: never;
    path: {
        mensagemId: string;
    };
    query?: never;
    url: '/api/v1/web/midias/{mensagemId}/conteudo';
};

export type BaixarMidiaWebResponses = {
    200: Blob | File;
};

export type BaixarMidiaWebResponse = BaixarMidiaWebResponses[keyof BaixarMidiaWebResponses];

export type EnviarModeloAprovadoWebData = {
    body: EntradaEnvioModeloWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/mensagens/modelo';
};

export type EnviarModeloAprovadoWebResponses = {
    200: MensagemCriadaWebDto;
};

export type EnviarModeloAprovadoWebResponse = EnviarModeloAprovadoWebResponses[keyof EnviarModeloAprovadoWebResponses];

export type ObterTimelineWebData = {
    body?: never;
    path: {
        atendimentoId: string;
    };
    query?: {
        cursor?: string;
    };
    url: '/api/v1/web/atendimentos/{atendimentoId}/timeline';
};

export type ObterTimelineWebResponses = {
    200: PaginaTimelineWebDto;
};

export type ObterTimelineWebResponse = ObterTimelineWebResponses[keyof ObterTimelineWebResponses];

export type ConfirmarLeituraTimelineWebData = {
    body: EntradaLeituraTimelineWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/leitura';
};

export type ConfirmarLeituraTimelineWebResponses = {
    200: MarcadorLeituraWebDto;
};

export type ConfirmarLeituraTimelineWebResponse = ConfirmarLeituraTimelineWebResponses[keyof ConfirmarLeituraTimelineWebResponses];

export type MarcarTimelineWebNaoLidaData = {
    body: EntradaMarcarNaoLidaWebDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        atendimentoId: string;
    };
    query?: never;
    url: '/api/v1/web/atendimentos/{atendimentoId}/marcar-nao-lida';
};

export type MarcarTimelineWebNaoLidaResponses = {
    200: MarcadorLeituraWebDto;
};

export type MarcarTimelineWebNaoLidaResponse = MarcarTimelineWebNaoLidaResponses[keyof MarcarTimelineWebNaoLidaResponses];

export type ListarFluxosEditorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/administracao/fluxos';
};

export type ListarFluxosEditorResponses = {
    200: Array<FluxoEditorDto>;
};

export type ListarFluxosEditorResponse = ListarFluxosEditorResponses[keyof ListarFluxosEditorResponses];

export type CriarFluxoEditorData = {
    body: EntradaCriacaoFluxoEditorDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/administracao/fluxos';
};

export type CriarFluxoEditorResponses = {
    201: FluxoCriadoEditorDto;
};

export type CriarFluxoEditorResponse = CriarFluxoEditorResponses[keyof CriarFluxoEditorResponses];

export type SimularFluxoEditorData = {
    body: EntradaSimulacaoFluxoDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/administracao/fluxos/simular';
};

export type SimularFluxoEditorResponses = {
    200: ResultadoSimulacaoFluxoDto;
};

export type SimularFluxoEditorResponse = SimularFluxoEditorResponses[keyof SimularFluxoEditorResponses];

export type ObterFluxoEditorData = {
    body?: never;
    path: {
        fluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}';
};

export type ObterFluxoEditorResponses = {
    200: FluxoEditorDto;
};

export type ObterFluxoEditorResponse = ObterFluxoEditorResponses[keyof ObterFluxoEditorResponses];

export type CriarVersaoFluxoEditorData = {
    body: EntradaNovaVersaoFluxoEditorDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        fluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}/versoes';
};

export type CriarVersaoFluxoEditorResponses = {
    201: VersaoFluxoEditorDto;
};

export type CriarVersaoFluxoEditorResponse = CriarVersaoFluxoEditorResponses[keyof CriarVersaoFluxoEditorResponses];

export type SalvarRascunhoFluxoEditorData = {
    body: EntradaSalvarRascunhoFluxoDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        fluxoId: string;
        versaoFluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}/versoes/{versaoFluxoId}/rascunho';
};

export type SalvarRascunhoFluxoEditorResponses = {
    200: VersaoFluxoEditorDto;
};

export type SalvarRascunhoFluxoEditorResponse = SalvarRascunhoFluxoEditorResponses[keyof SalvarRascunhoFluxoEditorResponses];

export type PrepararPublicacaoFluxoEditorData = {
    body: EntradaRevisaoVersaoFluxoDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        fluxoId: string;
        versaoFluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}/versoes/{versaoFluxoId}/preparar-publicacao';
};

export type PrepararPublicacaoFluxoEditorResponses = {
    200: ResultadoPreparacaoFluxoDto;
};

export type PrepararPublicacaoFluxoEditorResponse = PrepararPublicacaoFluxoEditorResponses[keyof PrepararPublicacaoFluxoEditorResponses];

export type PublicarVersaoFluxoEditorData = {
    body: EntradaRevisaoFluxoDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        fluxoId: string;
        versaoFluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}/versoes/{versaoFluxoId}/publicar';
};

export type PublicarVersaoFluxoEditorResponses = {
    200: ResultadoPublicacaoFluxoDto;
};

export type PublicarVersaoFluxoEditorResponse = PublicarVersaoFluxoEditorResponses[keyof PublicarVersaoFluxoEditorResponses];

export type ReverterVersaoFluxoEditorData = {
    body: EntradaRevisaoFluxoDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        fluxoId: string;
        versaoFluxoId: string;
    };
    query?: never;
    url: '/api/v1/administracao/fluxos/{fluxoId}/versoes/{versaoFluxoId}/reverter';
};

export type ReverterVersaoFluxoEditorResponses = {
    200: ResultadoPublicacaoFluxoDto;
};

export type ReverterVersaoFluxoEditorResponse = ReverterVersaoFluxoEditorResponses[keyof ReverterVersaoFluxoEditorResponses];

export type AvaliarVersaoMobileData = {
    body: EntradaAvaliacaoVersaoMobileDto;
    path?: never;
    query?: never;
    url: '/api/v1/configuracao/mobile/avaliar';
};

export type AvaliarVersaoMobileResponses = {
    200: AvaliacaoPoliticaVersaoMobileDto;
};

export type AvaliarVersaoMobileResponse = AvaliarVersaoMobileResponses[keyof AvaliarVersaoMobileResponses];

export type ObterConfiguracaoMobileAtualData = {
    body: EntradaAvaliacaoVersaoMobileDto;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/configuracao/mobile/atual';
};

export type ObterConfiguracaoMobileAtualResponses = {
    200: ConfiguracaoClienteMobileDto;
};

export type ObterConfiguracaoMobileAtualResponse = ObterConfiguracaoMobileAtualResponses[keyof ObterConfiguracaoMobileAtualResponses];

export type ObterConfiguracaoWebAtualData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/configuracao/web/atual';
};

export type ObterConfiguracaoWebAtualResponses = {
    200: ConfiguracaoClienteWebDto;
};

export type ObterConfiguracaoWebAtualResponse = ObterConfiguracaoWebAtualResponses[keyof ObterConfiguracaoWebAtualResponses];

export type ListarAdministracaoReleasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/administracao/releases';
};

export type ListarAdministracaoReleasesResponses = {
    200: AdministracaoReleasesDto;
};

export type ListarAdministracaoReleasesResponse = ListarAdministracaoReleasesResponses[keyof ListarAdministracaoReleasesResponses];

export type AtualizarControleRecursoData = {
    body: EntradaAtualizacaoControleRecursoDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        codigo: string;
    };
    query?: never;
    url: '/api/v1/administracao/releases/controles-recurso/{codigo}';
};

export type AtualizarControleRecursoResponses = {
    200: ControleRecursoDto;
};

export type AtualizarControleRecursoResponse = AtualizarControleRecursoResponses[keyof AtualizarControleRecursoResponses];

export type AtualizarPoliticaVersaoMobileData = {
    body: EntradaAtualizacaoPoliticaVersaoMobileDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        plataforma: string;
    };
    query?: never;
    url: '/api/v1/administracao/releases/politicas-mobile/{plataforma}';
};

export type AtualizarPoliticaVersaoMobileResponses = {
    200: PoliticaVersaoMobileDto;
};

export type AtualizarPoliticaVersaoMobileResponse = AtualizarPoliticaVersaoMobileResponses[keyof AtualizarPoliticaVersaoMobileResponses];

export type AcompanharEventosWebData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sincronizacao/eventos';
};

export type AcompanharEventosWebResponses = {
    200: unknown;
};

export type RessincronizarCompletaData = {
    body?: never;
    headers?: {
        'x-segredo-dispositivo'?: string;
        'x-dispositivo-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/sincronizacao/completa';
};

export type RessincronizarCompletaResponses = {
    200: SnapshotSincronizacaoDto;
};

export type RessincronizarCompletaResponse = RessincronizarCompletaResponses[keyof RessincronizarCompletaResponses];

export type SincronizarIncrementalData = {
    body?: never;
    headers?: {
        'x-segredo-dispositivo'?: string;
        'x-dispositivo-id'?: string;
    };
    path?: never;
    query?: {
        limite?: string;
        apos?: unknown;
    };
    url: '/api/v1/sincronizacao';
};

export type SincronizarIncrementalResponses = {
    200: LoteSincronizacaoDto;
};

export type SincronizarIncrementalResponse = SincronizarIncrementalResponses[keyof SincronizarIncrementalResponses];
