// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ErroCanonicoDto = {
    codigo: string;
    mensagem: string;
    correlacao_id: string;
};

export type InformacoesApiDto = {
    nome: string;
    versao_api: string;
};

export type EstadoSaudeDto = {
    estado: 'VIVO' | 'PRONTO';
};

export type EntradaLoginMobileDto = {
    identificador: string;
    senha: string;
    identificador_instalacao: string;
    segredo_vinculo: string;
    plataforma: 'IOS' | 'ANDROID';
    modelo_sanitizado?: string;
    versao_aplicativo: string;
};

export type SessaoMobileDto = {
    sessao_id: string;
    usuario_id: string;
    dispositivo_id: string;
    nome_exibicao: string;
    token_acesso: string;
    token_refresh: string;
    acesso_expira_em: string;
    refresh_expira_em: string;
};

export type EntradaRefreshMobileDto = {
    token_refresh: string;
};

export type ContextoSessaoMobileDto = {
    sessao_id: string;
    usuario_id: string;
    dispositivo_id: string;
    nome_exibicao: string;
    acesso_expira_em: string;
};

export type EntradaLoginWebDto = {
    /**
     * Confirma a substituição da sessão web ativa mais antiga quando o limite for alcançado.
     */
    confirmar_revogacao_sessao_mais_antiga?: boolean;
    identificador: string;
    senha: string;
};

export type SessaoWebDto = {
    sessao_id: string;
    usuario_id: string;
    nome_exibicao: string;
    expira_em: string;
};

export type ResumoSessaoWebDto = {
    sessao_id: string;
    atual: boolean;
    autenticada_em: string;
    ultima_atividade_em: string;
    expira_em: string;
};

export type ObterInformacoesApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1';
};

export type ObterInformacoesApiErrors = {
    500: ErroCanonicoDto;
};

export type ObterInformacoesApiError = ObterInformacoesApiErrors[keyof ObterInformacoesApiErrors];

export type ObterInformacoesApiResponses = {
    200: InformacoesApiDto;
};

export type ObterInformacoesApiResponse = ObterInformacoesApiResponses[keyof ObterInformacoesApiResponses];

export type VerificarProcessoVivoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/saude/vivo';
};

export type VerificarProcessoVivoResponses = {
    200: EstadoSaudeDto;
};

export type VerificarProcessoVivoResponse = VerificarProcessoVivoResponses[keyof VerificarProcessoVivoResponses];

export type VerificarAplicacaoProntaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/saude/pronto';
};

export type VerificarAplicacaoProntaErrors = {
    503: ErroCanonicoDto;
};

export type VerificarAplicacaoProntaError = VerificarAplicacaoProntaErrors[keyof VerificarAplicacaoProntaErrors];

export type VerificarAplicacaoProntaResponses = {
    200: EstadoSaudeDto;
};

export type VerificarAplicacaoProntaResponse = VerificarAplicacaoProntaResponses[keyof VerificarAplicacaoProntaResponses];

export type EntrarSessaoMobileData = {
    body: EntradaLoginMobileDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/entrar';
};

export type EntrarSessaoMobileResponses = {
    200: SessaoMobileDto;
};

export type EntrarSessaoMobileResponse = EntrarSessaoMobileResponses[keyof EntrarSessaoMobileResponses];

export type RenovarSessaoMobileData = {
    body: EntradaRefreshMobileDto;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/renovar';
};

export type RenovarSessaoMobileResponses = {
    200: SessaoMobileDto;
};

export type RenovarSessaoMobileResponse = RenovarSessaoMobileResponses[keyof RenovarSessaoMobileResponses];

export type ObterSessaoMobileData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/sessao';
};

export type ObterSessaoMobileResponses = {
    200: ContextoSessaoMobileDto;
};

export type ObterSessaoMobileResponse = ObterSessaoMobileResponses[keyof ObterSessaoMobileResponses];

export type SairSessaoMobileData = {
    body?: never;
    headers: {
        'x-segredo-dispositivo': string;
        'x-dispositivo-id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/mobile/sair';
};

export type SairSessaoMobileResponses = {
    204: void;
};

export type SairSessaoMobileResponse = SairSessaoMobileResponses[keyof SairSessaoMobileResponses];

export type EntrarSessaoWebData = {
    body: EntradaLoginWebDto;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/entrar';
};

export type EntrarSessaoWebResponses = {
    200: SessaoWebDto;
};

export type EntrarSessaoWebResponse = EntrarSessaoWebResponses[keyof EntrarSessaoWebResponses];

export type ListarSessoesWebData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sessoes';
};

export type ListarSessoesWebResponses = {
    200: Array<ResumoSessaoWebDto>;
};

export type ListarSessoesWebResponse = ListarSessoesWebResponses[keyof ListarSessoesWebResponses];

export type ObterSessaoWebData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sessao';
};

export type ObterSessaoWebResponses = {
    200: SessaoWebDto;
};

export type ObterSessaoWebResponse = ObterSessaoWebResponses[keyof ObterSessaoWebResponses];

export type RotacionarSessaoWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/rotacionar';
};

export type RotacionarSessaoWebResponses = {
    200: SessaoWebDto;
};

export type RotacionarSessaoWebResponse = RotacionarSessaoWebResponses[keyof RotacionarSessaoWebResponses];

export type SairSessaoWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sair';
};

export type SairSessaoWebResponses = {
    204: void;
};

export type SairSessaoWebResponse = SairSessaoWebResponses[keyof SairSessaoWebResponses];

export type SairTodasSessoesWebData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/autenticacao/web/sair-todas';
};

export type SairTodasSessoesWebResponses = {
    204: void;
};

export type SairTodasSessoesWebResponse = SairTodasSessoesWebResponses[keyof SairTodasSessoesWebResponses];

export type RevogarSessaoWebDoUsuarioData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        sessaoId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/sessoes/{sessaoId}/revogar';
};

export type RevogarSessaoWebDoUsuarioResponses = {
    204: void;
};

export type RevogarSessaoWebDoUsuarioResponse = RevogarSessaoWebDoUsuarioResponses[keyof RevogarSessaoWebDoUsuarioResponses];

export type RevogarSessoesWebAdministrativamenteData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        usuarioId: string;
    };
    query?: never;
    url: '/api/v1/autenticacao/web/usuarios/{usuarioId}/revogar-sessoes';
};

export type RevogarSessoesWebAdministrativamenteResponses = {
    204: void;
};

export type RevogarSessoesWebAdministrativamenteResponse = RevogarSessoesWebAdministrativamenteResponses[keyof RevogarSessoesWebAdministrativamenteResponses];
