import type {
  CodigoPermissaoAutorizacao,
  PapelBaseAutorizacao,
} from './modelo-autorizacao.js';

function congelarPermissoes(
  ...codigos: CodigoPermissaoAutorizacao[]
): readonly CodigoPermissaoAutorizacao[] {
  return Object.freeze(codigos);
}

export const MATRIZ_PERMISSOES_BASE = Object.freeze({
  ADMINISTRADOR: congelarPermissoes(
    'VISUALIZAR_FILA',
    'VISUALIZAR_FLUXO',
    'EDITAR_FLUXO',
    'TESTAR_FLUXO',
    'PUBLICAR_FLUXO',
    'REVERTER_FLUXO',
    'ADMINISTRAR_USUARIOS',
    'ADMINISTRAR_FILAS',
    'ADMINISTRAR_INTEGRACOES',
    'ADMINISTRAR_RELEASES',
    'ALTERAR_DISPONIBILIDADE_PROPRIA',
    'ALTERAR_DISPONIBILIDADE_USUARIO',
  ),
  SUPERVISOR: congelarPermissoes(
    'VISUALIZAR_FILA',
    'RESGATAR_ATENDIMENTO',
    'TRANSFERIR_ATENDIMENTO',
    'RECEBER_TRANSFERENCIA',
    'ENCERRAR_ATENDIMENTO',
    'REABRIR_ATENDIMENTO',
    'ASSUMIR_ATENDIMENTO',
    'ADICIONAR_NOTA_INTERNA',
    'VISUALIZAR_NOTA_INTERNA',
    'SOLICITAR_FORMULARIO_WHATSAPP',
    'ALTERAR_DISPONIBILIDADE_PROPRIA',
    'ALTERAR_DISPONIBILIDADE_USUARIO',
  ),
  ATENDENTE: congelarPermissoes(
    'VISUALIZAR_FILA',
    'RESGATAR_ATENDIMENTO',
    'TRANSFERIR_ATENDIMENTO',
    'RECEBER_TRANSFERENCIA',
    'ENCERRAR_ATENDIMENTO',
    'ADICIONAR_NOTA_INTERNA',
    'VISUALIZAR_NOTA_INTERNA',
    'SOLICITAR_FORMULARIO_WHATSAPP',
    'ALTERAR_DISPONIBILIDADE_PROPRIA',
  ),
} satisfies Readonly<
  Record<PapelBaseAutorizacao, readonly CodigoPermissaoAutorizacao[]>
>);

export const PERMISSOES_COM_ESCOPO_FILA = new Set<CodigoPermissaoAutorizacao>([
  'VISUALIZAR_FILA',
  'RESGATAR_ATENDIMENTO',
  'TRANSFERIR_ATENDIMENTO',
  'RECEBER_TRANSFERENCIA',
  'ENCERRAR_ATENDIMENTO',
  'REABRIR_ATENDIMENTO',
  'ASSUMIR_ATENDIMENTO',
  'ADICIONAR_NOTA_INTERNA',
  'VISUALIZAR_NOTA_INTERNA',
  'CONSULTAR_CLIENTE',
  'VINCULAR_CLIENTE',
  'ALTERAR_CONTEXTO_CLIENTE',
  'CONSULTAR_CONTRATO',
  'CONSULTAR_FINANCEIRO',
  'ENVIAR_FATURA',
  'VERIFICAR_DESBLOQUEIO_CONFIANCA',
  'EXECUTAR_DESBLOQUEIO_CONFIANCA',
  'CONSULTAR_SESSAO_ACESSO',
  'DESCONECTAR_SESSAO_ACESSO',
  'CRIAR_ORDEM_SERVICO',
  'SOLICITAR_FORMULARIO_WHATSAPP',
]);

export const PERMISSOES_SEMPRE_EXPLICITAS = new Set<CodigoPermissaoAutorizacao>([
  'VISUALIZAR_HISTORICO_TRANSVERSAL',
  'VISUALIZAR_NOTAS_TRANSVERSAIS',
  'VISUALIZAR_DADO_SENSIVEL',
  'EXPORTAR_HISTORICO',
]);
